# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cobject.proto\"\x88\x01\n\x06Object\x12\t\n\x01i\x18\x01 \x01(\x05\x12\r\n\x05\x62ig_i\x18\x02 \x01(\x03\x12\t\n\x01\x66\x18\x03 \x01(\x02\x12\x19\n\x01m\x18\x04 \x03(\x0b\x32\x0e.Object.MEntry\x12\t\n\x01\x61\x18\x05 \x03(\x05\x12\t\n\x01s\x18\x06 \x01(\t\x1a(\n\x06MEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECT_MENTRY._options = None
  _OBJECT_MENTRY._serialized_options = b'8\001'
  _OBJECT._serialized_start=17
  _OBJECT._serialized_end=153
  _OBJECT_MENTRY._serialized_start=113
  _OBJECT_MENTRY._serialized_end=153
# @@protoc_insertion_point(module_scope)
